export default {
    classes: [
        { key: 1, label: 'Bard' },
        { key: 2, label: 'Barbarian' },
        { key: 3, label: 'Cleric' },
        { key: 4, label: 'Druid' },
        { key: 5, label: 'Fighter' },
        { key: 6, label: 'Monk' },
        { key: 7, label: 'Paladin' },
        { key: 8, label: 'Ranger' },
        { key: 9, label: 'Rogue' },
        { key: 10, label: 'Sorcerer' },
        { key: 11, label: 'Warlock' },
        { key: 12, label: 'Wizard' },
    ],
    races: [
        { key: 1, label: 'Dragonborn' },
        { key: 2, label: 'Dwarf' },
        { key: 3, label: 'Elf' },
        { key: 4, label: 'Gnome' },
        { key: 5, label: 'Half-Elf' },
        { key: 6, label: 'Halfling' },
        { key: 7, label: 'Half-Orc' },
        { key: 8, label: 'Human' },
        { key: 9, label: 'Tiefling' },
        { key: 10, label: 'Arakocra' },
        { key: 11, label: 'Genasi' },
        { key: 12, label: 'Goliath' },
        { key: 13, label: 'Aasimar' },
        { key: 14, label: 'Bugbear' },
        { key: 15, label: 'Firbolg' },
        { key: 16, label: 'Goblin' },
        { key: 17, label: 'Hobgoblin' },
        { key: 18, label: 'Kenku'},
        { key: 19, label: 'Kobold' },
        { key: 20, label: 'Triton' },
        { key: 21, label: 'Yuan-ti Pureblood' },
        { key: 22, label: 'Tortle' },
        { key: 23, label: 'Gith' },
        { key: 24, label: 'Changeling' },
        { key: 25, label: 'Kalashtar' },
        { key: 26, label: 'Shifter' },
        { key: 27, label: 'Warforged' },
        { key: 28, label: 'Centaur' },
        { key: 29, label: 'Loxodon' },
        { key: 30, label: 'Minotaur' },
        { key: 31, label: 'Simic Hybrid' },
        { key: 32, label: 'Vedalken' },
        { key: 33, label: 'Tabaxi'},
    ],
  };